### ISSUE TITLE
Extension jeppeandersen.vscode-kafka has provided an invalid tree item.

### ISSUE THREAD

**Issue by alberttwong** [jlandersen/vscode-kafka#245] opened 2024-04-26 16:42 UTC
I'm trying to browse a debezium message and I got the above message. 

```
[kafka@ab2849ae2462 ~]$ bin/kafka-console-consumer.sh --bootstrap-server kafka:29092 --topic postgres.public.customer --from-beginning
{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":true,"field":"col_001"},{"type":"string","optional":true,"field":"col_002"},{"type":"int32","optional":true,"field":"col_003"},{"type":"int32","optional":true,"field":"col_004"},{"type":"int32","optional":true,"field":"col_005"},{"type":"int32","optional":true,"field":"col_006"},{"type":"int32","optional":true,"field":"col_007"},{"type":"string","optional":true,"field":"col_008"},{"type":"string","optional":true,"field":"col_009"},{"type":"string","optional":true,"field":"col_010"},{"type":"string","optional":true,"field":"col_011"},{"type":"int32","optional":true,"field":"col_012"},{"type":"int32","optional":true,"field":"col_013"},{"type":"int32","optional":true,"field":"col_014"},{"type":"string","optional":true,"field":"col_015"},{"type":"string","optional":true,"field":"col_016"},{"type":"string","optional":true,"field":"col_017"},{"type":"int32","optional":true,"field":"col_018"},{"type":"int64","optional":true,"field":"_sling_loaded_at"}],"optional":true,"name":"postgres.public.customer.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":true,"field":"col_001"},{"type":"string","optional":true,"field":"col_002"},{"type":"int32","optional":true,"field":"col_003"},{"type":"int32","optional":true,"field":"col_004"},{"type":"int32","optional":true,"field":"col_005"},{"type":"int32","optional":true,"field":"col_006"},{"type":"int32","optional":true,"field":"col_007"},{"type":"string","optional":true,"field":"col_008"},{"type":"string","optional":true,"field":"col_009"},{"type":"string","optional":true,"field":"col_010"},{"type":"string","optional":true,"field":"col_011"},{"type":"int32","optional":true,"field":"col_012"},{"type":"int32","optional":true,"field":"col_013"},{"type":"int32","optional":true,"field":"col_014"},{"type":"string","optional":true,"field":"col_015"},{"type":"string","optional":true,"field":"col_016"},{"type":"string","optional":true,"field":"col_017"},{"type":"int32","optional":true,"field":"col_018"},{"type":"int64","optional":true,"field":"_sling_loaded_at"}],"optional":true,"name":"postgres.public.customer.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":false,"field":"ts_us"},{"type":"int64","optional":false,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"postgres.public.customer.Envelope","version":2},"payload":{"before":null,"after":{"col_001":1,"col_002":"AAAAAAAABAAAAAAA","col_003":980124,"col_004":7135,"col_005":32946,"col_006":2452238,"col_007":2452208,"col_008":"Mr.","col_009":"Javier","col_010":"Lewis","col_011":"Y","col_012":9,"col_013":12,"col_014":1936,"col_015":"CHILE","col_016":null,"col_017":"Javier.Lewis@VFAxlnZEvOx.org","col_018":2452508,"_sling_loaded_at":1714149477},"source":{"version":"2.6.1.Final","connector":"postgresql","name":"postgres","ts_ms":1714149477950,"snapshot":"false","db":"postgres","sequence":"[\"23170000\",\"23190448\"]","ts_us":1714149477950374,"ts_ns":1714149477950374000,"schema":"public","table":"customer","txId":745,"lsn":23190448,"xmin":null},"op":"c","ts_ms":1714149477976,"ts_us":1714149477976084,"ts_ns":1714149477976084000,"transaction":null}}
```

**Comment by fbricon** [comment] 2024-04-26 17:14
Closing as duplicate of #234

unfortunately we have no spare cycles to troubleshoot vscode-kafka at the moment. You'll need to do some debugging

**Closed by fbricon** 2024-04-26 17:14 UTC
