### ISSUE TITLE
Failed operation - Broker not available(loadMetadataForTopics)

### ISSUE THREAD

**Issue by yury-gurevich** [jlandersen/vscode-kafka#19] opened 2020-09-27 02:30 UTC
GREAT WORK. You saved me so much time. Thank you, thank you.

After switching focus message "Failed operation - Broker not available(loadMetadataForTopics)" comes up.
Restarting VSCode resoles he issue, but after a while ( cannot correlate this with any event I can think of ) the extension stops responding again until next restart fixes the issue.

I am happy to supply you with any diagnostic material you need to continue improving this very useful tool.
Thank you again

**Comment by jlandersen** [comment] 2020-09-27 10:17
thanks for the kind words :)

my guess is a connection is closed and/or metadata about the cluster is lost after a while and not refreshed as expected. I'll take a look at what I can find.

**Comment by fbricon** [comment] 2021-01-17 09:49
Since we switched the underlying client library,  is this issue still relevant with the latest version of vscode-kafka?
@yury-gurevich can you still reproduce the problem?

**Comment by angelozerr** [comment] 2021-03-15 08:52
I close this issue since I cannot reproduce it and since we consume now kafkajs.

@yury-gurevich if you find this issue again, please reopen it and give us more detail how to reproduce it. Thanks!

**Closed by angelozerr** 2021-03-15 08:52 UTC
Labels: bug, topics
