### ISSUE TITLE
Unable to add cluster

### ISSUE THREAD

**Issue by Evynglais** [jlandersen/vscode-kafka#212] opened 2021-11-09 14:10 UTC
Hi, getting the following page when attempting to add a cluster:

![image](https://user-images.githubusercontent.com/71874625/140939112-347dfb57-01e3-4599-9661-6074cdc773db.png)

Any ideas on what's going wrong?

Thanks,
Evynglais

**Comment by fbricon** [comment] 2021-11-09 14:53
Closing as duplicate of #211

**Closed by fbricon** 2021-11-09 14:53 UTC
