### ISSUE TITLE
It'd be nice to support purging messages within a topic (without deleting the topic)

### ISSUE THREAD

**Issue by tigerinus** [jlandersen/vscode-kafka#207] opened 2021-07-27 16:19 UTC
Been using https://www.conduktor.io/ for a while, until recently they've stopped providing some critical features in free version.

One of the features is be able to purge the messages within a topic (without deleting the topic).

It'd be nice for this extension to support this feature. 

Kudos to the extension author!

**Comment by fbricon** [comment] 2021-07-27 16:28
Closing as duplicate of https://github.com/jlandersen/vscode-kafka/issues/31

**Closed by fbricon** 2021-07-27 16:28 UTC
Labels: duplicate
