### ISSUE TITLE
Add on option to select topic view "from-beginning"

### ISSUE THREAD

**Issue by Varrkan82** [jlandersen/vscode-kafka#43] opened 2020-12-08 15:40 UTC
Please, add an option to make it possible to view kafka topic from beginning. Like a CLI parameter "--from-beginning"

**Comment by fbricon** [comment] 2020-12-09 18:13
Looks like a duplicate of https://github.com/jlandersen/vscode-kafka/issues/9

**Comment by Varrkan82** [comment] 2020-12-09 22:19
> Looks like a duplicate of https://github.com/jlandersen/vscode-kafka/issues/9

It is looks like, but not the same if to be precise. In https://github.com/jlandersen/vscode-kafka/issues/9 it is asked to implement feature to retrieve data by a date and as it commented below - it is could be hard to implement. But my request about fetching an all data from the beginning and it could be easier to do. But any way - an ideas looks the same in total - to get data earlier than consumer connected to the topic.

**Comment by fbricon** [comment] 2020-12-09 23:14
> but does not allow querying or consuming the entire topic to see all results.

all results == since the beginning == having no date filter. So yeah fixing #9 fixes this one. If kafkajs exposes the right things, it should not be overly difficult to implement. Just need to figure out a good UX.

**Comment by fbricon** [comment] 2020-12-14 10:24
BTW, there's already a preference key, `"kafka.consumers.offset"="earliest"`,  that lets consumers read topics from the beginning:
<img width="1040" alt="Screenshot 2020-12-14 at 11 21 49" src="https://user-images.githubusercontent.com/148698/102069959-c02b9000-3dfe-11eb-9975-204de648f7af.png">

It's not a per-consumer setting for now but I think we should change that, when creating consumers.

**Comment by angelozerr** [comment] 2021-02-17 15:04
I think this issue will be covered by https://github.com/jlandersen/vscode-kafka/issues/96 by using `from: earliest`

**Comment by angelozerr** [comment] 2021-02-26 09:59
Fixed with https://github.com/jlandersen/vscode-kafka/pull/98 by using `from`  with CONSUMER kafkafile.

See https://github.com/jlandersen/vscode-kafka/blob/master/docs/Consuming.md#kafka-file for more information.

**Closed by angelozerr** 2021-02-26 09:59 UTC
Labels: enhancement, topics
